import { PubSub } from 'graphql-subscriptions'

export const pubsub = new PubSub()

export const EVENTS = {
  GAME_ADDED: 'GAME_ADDED',
  GAME_UPDATED: 'GAME_UPDATED',
  GAME_DELETED: 'GAME_DELETED',
  REVIEW_ADDED: 'REVIEW_ADDED',
  REVIEW_UPDATED: 'REVIEW_UPDATED',
  REVIEW_DELETED: 'REVIEW_DELETED',
  AUTHOR_ADDED: 'AUTHOR_ADDED',
  AUTHOR_UPDATED: 'AUTHOR_UPDATED',
  AUTHOR_DELETED: 'AUTHOR_DELETED',
}
